server:
  port: 9999


spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/phoneshop
    username: postgres
    password: admin
  h2:
    console:
      enabled: true

  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  #disable SerializationFeature
  jackson:
    serialization:
      fail-on-empty-beans: false

